name: .NET

on:
  push:
    branches: [ master, testing ]
  pull_request:
    branches: [ master, testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Environment Name
      id: envname
      run: echo "::set-output name=envname::$(envname + 'LearningPipelin2-${GITHUB_REF##*/}')"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run:  dotnet publish --configuration "Debug" --framework "net5.0"  --runtime linux-x64 --self-contained false
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
    - name: Generate deployment package
      run: cd bin/Debug/net5.0/linux-x64/publish; zip -r deploy.zip . -x '*.git*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: LearningPipelin2
        environment_name: ${{ steps.envname.outputs.envname }}
        version_label: ${{ steps.date.outputs.date }}
        region: us-east-1
        deployment_package: bin/Debug/net5.0/linux-x64/publish/deploy.zip
